# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  frontStoreImageName: 'rookiecom-frontstore'
  webApiImageName: 'rookiecom-webapi'
  identityServerImageName: 'rookiecom-identityserver'
  backofficeImageName: 'rookiecom-backoffice'

stages:
- stage: Build
  displayName: Build Docker Images
  jobs:
  - job: BuildAllImages
    displayName: Build Application Images
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build FrontStore image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Hosts/RookiEcom.FrontStore/Dockerfile'
        repository: $(frontStoreImageName)
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Build IdentityServer Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Hosts/RookiEcom.IdentityServer/Dockerfile'
        repository: $(identityServerImageName)
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Build WebAPI Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Hosts/RookiEcom.WebAPI/Dockerfile'
        repository: $(webApiImageName)
        tags: |
          $(tag)
          latest
    
    - task: Docker@2
      displayName: 'Build Backoffice Image'
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Hosts/RookiEcom.BackOffice/Dockerfile'
        repository: $(backofficeImageName)
        tags: |
          $(tag)
          latest
          buildArgs: |
          VITE_API_URL=0.0.0.0:7670
